### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by susobaco** [danielesteban/Gatunes#2]
Hi, congratulations on the application. I ask for the license code, is GPL? Thank you!

**Comment by danielesteban** [comment]
I didn't release the app source code just yet.. but when I do, it's probably gonna be an MIT license.
What you see at the moment on this repo is just the landing page source code and the app releases.

I'll Keep this issue open to notify you when it's up.

Peace!

**Comment by danielesteban** [comment]
Hi again.

I just uploaded the whole source to this repo... and as I predicted, the final license happens to be MIT.
I'm gonna close this issue now.

P.S.: Pull-requests are welcome ;P

**Comment by susobaco** [comment]
Thank you!
